const CREATE_USER = 'CREATE_USER';
const CREATE_USER_LOADING = 'CREATE_USER_LOADING';
const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
const CREATE_GROUP = 'CREATE_GROUP';
const CREATE_SUBJECT = 'CREATE_SUBJECT';
const CREATE_TIME = 'CREATE_TIME';
const CREATE_ROOM= 'CREATE_ROOM';

export {CREATE_USER, CREATE_GROUP, CREATE_SUBJECT, CREATE_TIME,  CREATE_ROOM, CREATE_USER_LOADING, CREATE_USER_ERROR}