const CREATE= 'CREATE';
const CREATE_LOADING= 'CREATE_LOADING';
const CREATE_ERROR= 'CREATE_ERROR';
const GET_USER = 'GET_USER'
const GET_ROOM = 'GET_ROOM'
const GET_TIME = 'GET_TIME'
const GET_SUBJECT = 'GET_SUBJECT'
const GET_GROUP = 'GET_GROUP'

export {CREATE_ERROR, CREATE_LOADING, GET_USER, GET_ROOM, GET_TIME, GET_SUBJECT, GET_GROUP, CREATE}